# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Slacking Space
email: nikolas@phoa.me
description: >
  Learning something while slacking
logo: "assets/images/logo.jpg"
favicon: "assets/images/favicon.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://slacking.space" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
name: 'Nikolas'
bio: >
  Web Developer
twitter_username: nikokin6
github_username:  nikolas6

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
